const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('securityApi', {
    getStats: () => ipcRenderer.invoke('get-stats'),
    getConfig: () => ipcRenderer.invoke('get-config'),
    setEnabled: (val) => ipcRenderer.send('set-enabled', val),
    setHistoryEnabled: (val) => ipcRenderer.send('set-history-enabled', val),
    setVTKey: (key) => ipcRenderer.send('set-vt-key', key),
    setSpamKeywords: (keywords) => ipcRenderer.send('set-spam-keywords', keywords),
    setRubrics: (rubrics) => ipcRenderer.send('set-rubrics', rubrics),
    setWhitelist: (whitelist) => ipcRenderer.send('set-whitelist', whitelist),
    setSchedule: (val) => ipcRenderer.send('set-schedule', val),
    saveColumnWidths: (widths) => ipcRenderer.send('save-column-widths', widths),
    openLogsFolder: () => ipcRenderer.send('open-logs-folder'),
    resetApp: () => ipcRenderer.send('app-reset'),
    releaseEmail: (data) => ipcRenderer.send('release-email', data),
    checkPowerStatus: () => ipcRenderer.invoke('check-power-status'),
    overridePowerPlan: () => ipcRenderer.send('override-power-plan'),
    backupConfig: () => ipcRenderer.invoke('backup-config'),
    restoreConfig: () => ipcRenderer.invoke('restore-config'),
    onOutlookScanUpdate: (callback) => ipcRenderer.on('outlook-scan-update', (event, data) => callback(data)),
    onScanFinished: (callback) => ipcRenderer.on('scan-finished', (event, mode) => callback(mode)),
    onStatusSync: (callback) => ipcRenderer.on('status-sync', (event, val) => callback(val)),
    onEmailReleased: (callback) => ipcRenderer.on('email-released-success', (event, id) => callback(id)),
    onEmailReleasedError: (callback) => ipcRenderer.on('email-released-error', (event, data) => callback(data)),
    onStatsUpdate: (callback) => ipcRenderer.on('stats-update', (event, data) => callback(data))
});